// Generated by CoffeeScript 2.1.1
(function() {
  /*
    BeSafe! - For all your security needs
    Copyright (C) 2018  Ma124

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
  */
  window.hash = function(v) {
    var md, out;
    md = eval("forge.md." + document.getElementById("algorithm").value.toLowerCase().replace("-", "").replace("/", ".sha") + ".create()");
    md.update(v);
    out = md.digest();
    document.getElementById("hex").value = out.toHex();
    return document.getElementById("b64").value = forge.util.encode64(out.data);
  };

  window.regen_hash = function() {
    return hash(document.getElementById("input").value);
  };

}).call(this);

//# sourceMappingURL=hash.js.map
